# Copyright (c) 2020-2026 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause

FROM redhat/ubi10:latest

ARG http_proxy_env
ARG https_proxy_env
ARG DGPU_LTS_OS_SUPPORT="10.0"

# repository to install Intel(R) oneAPI Libraries
RUN tee /etc/yum.repos.d/oneAPI.repo <<'EOF'
[oneAPI]
name=Intel® oneAPI repository
baseurl=https://yum.repos.intel.com/oneapi
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
EOF

RUN cat <<EOF >> /etc/dnf/dnf.conf
metadata_timer_sync=0
proxy=${https_proxy_env}
EOF

RUN dnf install epel-release -y && \
    dnf config-manager --enable crb && \
    dnf install https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm -y && \
    dnf repolist; dnf makecache -y

# repository to install Intel(R) GPU drivers
RUN VERSION_ID=$(. /etc/os-release ; echo -n $VERSION_ID) && echo VERSION_ID=${VERSION_ID}; echo '' && \
    https_proxy=${https_proxy_env} rpm --import https://repositories.intel.com/gpu/intel-graphics.key && \
    dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo https://repositories.intel.com/gpu/rhel/${DGPU_LTS_OS_SUPPORT}/lts/2523/unified/intel-gpu-${DGPU_LTS_OS_SUPPORT}.repo &&  \
    dnf repolist; dnf makecache -y

RUN yum update -y && \
    yum install -y cmake procps make gcc gcc-c++ pkgconfig which bzip2 openssh-server openssh-clients \
                    wget net-tools git diffutils cmake intel-deep-learning-essentials \
                    intel-opencl intel-level-zero-gpu level-zero level-zero-devel

ENV LANG=C.UTF-8
ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
ENV CCL_CONFIGURATION_PATH=''
ENV CCL_ROOT='/opt/intel/oneapi/ccl/2021.17'
ENV CLASSPATH='/opt/intel/oneapi/mpi/2021.17/share/java/mpi.jar'
ENV CMAKE_PREFIX_PATH='/opt/intel/oneapi/tbb/2022.3/env/..:/opt/intel/oneapi/pti/0.16/lib/cmake/pti:/opt/intel/oneapi/mkl/2025.3/lib/cmake:/opt/intel/oneapi/dpl/2022.10/lib/cmake/oneDPL:/opt/intel/oneapi/dnnl/2025.3/lib/cmake:/opt/intel/oneapi/compiler/2025.3:/opt/intel/oneapi/ccl/2021.17/lib/cmake/oneCCL'
ENV CMPLR_ROOT='/opt/intel/oneapi/compiler/2025.3'
ENV CPATH='/opt/intel/oneapi/umf/1.0/include:/opt/intel/oneapi/mkl/2025.3/include:/opt/intel/oneapi/dev-utilities/2025.3/include:/opt/intel/oneapi/ccl/2021.17/include'
ENV CPLUS_INCLUDE_PATH='/opt/intel/oneapi/umf/1.0/include:/opt/intel/oneapi/tbb/2022.3/env/../include:/opt/intel/oneapi/pti/0.16/include:/opt/intel/oneapi/mpi/2021.17/include:/opt/intel/oneapi/mkl/2025.3/include:/opt/intel/oneapi/dpl/2022.10/include:/opt/intel/oneapi/dnnl/2025.3/include'
ENV C_INCLUDE_PATH='/opt/intel/oneapi/umf/1.0/include:/opt/intel/oneapi/tbb/2022.3/env/../include:/opt/intel/oneapi/pti/0.16/include:/opt/intel/oneapi/mpi/2021.17/include:/opt/intel/oneapi/mkl/2025.3/include:/opt/intel/oneapi/dnnl/2025.3/include'
ENV DIAGUTIL_PATH='/opt/intel/oneapi/compiler/2025.3/etc/compiler/sys_check/sys_check.sh'
ENV DNNLROOT='/opt/intel/oneapi/dnnl/2025.3'
ENV DPLROOT='/opt/intel/oneapi/dpl/2022.10'
ENV DPL_ROOT='/opt/intel/oneapi/dpl/2022.10'
ENV FI_PROVIDER_PATH='/opt/intel/oneapi/mpi/2021.17/opt/mpi/libfabric/lib/prov:/usr/lib64/libfabric'
ENV GDB_INFO='/opt/intel/oneapi/debugger/2025.3/share/info/'
ENV INFOPATH='/opt/intel/oneapi/debugger/2025.3/share/info'
ENV INTEL_PYTHONHOME='/opt/intel/oneapi/debugger/2025.3/opt/debugger'
ENV I_MPI_ROOT='/opt/intel/oneapi/mpi/2021.17'
ENV LD_LIBRARY_PATH='/opt/intel/oneapi/tcm/1.4/lib:/opt/intel/oneapi/umf/1.0/lib:/opt/intel/oneapi/tbb/2022.3/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/pti/0.16/lib:/opt/intel/oneapi/mpi/2021.17/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.17/lib:/opt/intel/oneapi/mkl/2025.3/lib:/opt/intel/oneapi/dnnl/2025.3/lib:/opt/intel/oneapi/debugger/2025.3/opt/debugger/lib:/opt/intel/oneapi/compiler/2025.3/opt/compiler/lib:/opt/intel/oneapi/compiler/2025.3/lib:/opt/intel/oneapi/ccl/2021.17/lib/'
ENV LIBRARY_PATH='/opt/intel/oneapi/tcm/1.4/lib:/opt/intel/oneapi/umf/1.0/lib:/opt/intel/oneapi/tbb/2022.3/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/pti/0.16/lib:/opt/intel/oneapi/mpi/2021.17/lib:/opt/intel/oneapi/mkl/2025.3/lib:/opt/intel/oneapi/dnnl/2025.3/lib:/opt/intel/oneapi/compiler/2025.3/lib:/opt/intel/oneapi/ccl/2021.17/lib/'
ENV MANPATH='/opt/intel/oneapi/mpi/2021.17/share/man:/opt/intel/oneapi/debugger/2025.3/share/man:/opt/intel/oneapi/compiler/2025.3/share/man:'
ENV MKLROOT='/opt/intel/oneapi/mkl/2025.3'
ENV NLSPATH='/opt/intel/oneapi/compiler/2025.3/lib/compiler/locale/%l_%t/%N'
ENV OCL_ICD_FILENAMES='/opt/intel/oneapi/compiler/2025.3/lib/libintelocl.so'
ENV ONEAPI_ROOT='/opt/intel/oneapi'
ENV PATH='/opt/intel/oneapi/mpi/2021.17/bin:/opt/intel/oneapi/mkl/2025.3/bin:/opt/intel/oneapi/dev-utilities/2025.3/bin:/opt/intel/oneapi/debugger/2025.3/opt/debugger/bin:/opt/intel/oneapi/compiler/2025.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
ENV PKG_CONFIG_PATH='/opt/intel/oneapi/tbb/2022.3/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.17/lib/pkgconfig:/opt/intel/oneapi/mkl/2025.3/lib/pkgconfig:/opt/intel/oneapi/dpl/2022.10/lib/pkgconfig:/opt/intel/oneapi/dnnl/2025.3/lib/pkgconfig:/opt/intel/oneapi/compiler/2025.3/lib/pkgconfig:/opt/intel/oneapi/ccl/2021.17/lib/pkgconfig/'
ENV Pti_DIR='/opt/intel/oneapi/pti/0.16/lib/cmake/pti'
ENV SETVARS_COMPLETED='1'
ENV TBBROOT='/opt/intel/oneapi/tbb/2022.3/env/..'
ENV TCM_ROOT='/opt/intel/oneapi/tcm/1.4'
ENV UMF_ROOT='/opt/intel/oneapi/umf/1.0'
