# Copyright (c) 2020-2021 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause

FROM ubuntu:20.04 as build

RUN mkdir -p /opt/build && mkdir -p /opt/dist
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates curl && \
  rm -rf /var/lib/apt/lists/*

# install cmake
RUN cd /opt/build && \
    curl -LO https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-linux-x86_64.sh && \
    mkdir -p /opt/dist//usr/local && \
    /bin/bash cmake-3.24.3-linux-x86_64.sh --prefix=/opt/dist//usr/local --skip-license






# cleanup
RUN rm -rf /opt/dist/usr/local/include && \
    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
RUN rm -rf /opt/dist/usr/local/share/doc
RUN rm -rf /opt/dist/usr/local/share/man

FROM ubuntu:20.04
COPY third-party-programs.txt /
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
  rm -rf /var/lib/apt/lists/*
# repository to install Intel(R) oneAPI Libraries
RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | apt-key add -
RUN echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
  rm -rf /var/lib/apt/lists/*
# repository to install Intel(R) GPU drivers
RUN curl -fsSL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
RUN echo "deb [trusted=yes arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main" > /etc/apt/sources.list.d/intel-graphics.list

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git intel-basekit-getting-started intel-oneapi-advisor intel-oneapi-ccl-devel intel-oneapi-common-licensing intel-oneapi-common-vars intel-oneapi-compiler-dpcpp-cpp intel-oneapi-dal-devel intel-oneapi-dev-utilities intel-oneapi-dnnl-devel intel-oneapi-dpcpp-debugger intel-oneapi-ipp-devel intel-oneapi-ippcp-devel intel-oneapi-libdpstd-devel intel-oneapi-mkl-devel intel-oneapi-onevpl-devel intel-oneapi-python intel-oneapi-tbb-devel intel-oneapi-vtune intel-opencl-icd intel-level-zero-gpu level-zero level-zero-dev intel-hpckit-getting-started intel-oneapi-clck intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-compiler-fortran intel-oneapi-inspector intel-oneapi-itac intel-oneapi-mpi-devel  && \
  rm -rf /var/lib/apt/lists/*

COPY --from=build /opt/dist /

ENV LANG=C.UTF-8
ENV ACL_BOARD_VENDOR_PATH='/opt/Intel/OpenCLFPGA/oneAPI/Boards'
ENV ADVISOR_2022_DIR='/opt/intel/oneapi/advisor/2022.3.1'
ENV APM='/opt/intel/oneapi/advisor/2022.3.1/perfmodels'
ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
ENV CCL_ROOT='/opt/intel/oneapi/ccl/2021.7.1'
ENV CLASSPATH='/opt/intel/oneapi/mpi/2021.7.1//lib/mpi.jar:/opt/intel/oneapi/dal/2021.7.1/lib/onedal.jar'
ENV CLCK_ROOT='/opt/intel/oneapi/clck/2021.7.1'
ENV CMAKE_PREFIX_PATH='/opt/intel/oneapi/vpl/2022.2.5:/opt/intel/oneapi/tbb/2021.7.1/env/..:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/../lib/cmake:/opt/intel/oneapi/dal/2021.7.1:/opt/intel/oneapi/compiler/2022.2.1/linux/IntelDPCPP'
ENV CMPLR_ROOT='/opt/intel/oneapi/compiler/2022.2.1'
ENV CONDA_DEFAULT_ENV='intelpython-python3.9'
ENV CONDA_EXE='/opt/intel/oneapi/intelpython/latest/bin/conda'
ENV CONDA_PREFIX='/opt/intel/oneapi/intelpython/latest'
ENV CONDA_PROMPT_MODIFIER='(intelpython-python3.9) '
ENV CONDA_PYTHON_EXE='/opt/intel/oneapi/intelpython/latest/bin/python'
ENV CONDA_SHLVL='1'
ENV CPATH='/opt/intel/oneapi/vpl/2022.2.5/include:/opt/intel/oneapi/tbb/2021.7.1/env/../include:/opt/intel/oneapi/mpi/2021.7.1//include:/opt/intel/oneapi/mkl/2022.2.1/include:/opt/intel/oneapi/ippcp/2021.6.2/include:/opt/intel/oneapi/ipp/2021.6.2/include:/opt/intel/oneapi/dpl/2021.7.2/linux/include:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/include:/opt/intel/oneapi/dev-utilities/2021.7.1/include:/opt/intel/oneapi/dal/2021.7.1/include:/opt/intel/oneapi/ccl/2021.7.1/include/cpu_gpu_dpcpp'
ENV CPLUS_INCLUDE_PATH='/opt/intel/oneapi/clck/2021.7.1/include'
ENV DAALROOT='/opt/intel/oneapi/dal/2021.7.1'
ENV DALROOT='/opt/intel/oneapi/dal/2021.7.1'
ENV DAL_MAJOR_BINARY='1'
ENV DAL_MINOR_BINARY='1'
ENV DIAGUTIL_PATH='/opt/intel/oneapi/vtune/2022.4.1/sys_check/vtune_sys_check.py:/opt/intel/oneapi/debugger/2021.7.1/sys_check/debugger_sys_check.py:/opt/intel/oneapi/compiler/2022.2.1/sys_check/sys_check.sh:/opt/intel/oneapi/advisor/2022.3.1/sys_check/advisor_sys_check.py:'
ENV DNNLROOT='/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp'
ENV DPL_ROOT='/opt/intel/oneapi/dpl/2021.7.2'
ENV FI_PROVIDER_PATH='/opt/intel/oneapi/mpi/2021.7.1//libfabric/lib/prov:/usr/lib64/libfabric'
ENV FPGA_VARS_ARGS=''
ENV FPGA_VARS_DIR='/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga'
ENV GDB_INFO='/opt/intel/oneapi/debugger/2021.7.1/documentation/info/'
ENV INFOPATH='/opt/intel/oneapi/debugger/2021.7.1/gdb/intel64/lib'
ENV INSPECTOR_2022_DIR='/opt/intel/oneapi/inspector/2022.3.1'
ENV INTELFPGAOCLSDKROOT='/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga'
ENV INTEL_LICENSE_FILE='/opt/intel/licenses:/root/intel/licenses:/opt/intel/oneapi/clck/2021.7.1/licensing:/opt/intel/licenses:/root/intel/licenses:/Users/Shared/Library/Application Support/Intel/Licenses'
ENV INTEL_PYTHONHOME='/opt/intel/oneapi/debugger/2021.7.1/dep'
ENV IPPCP_TARGET_ARCH='intel64'
ENV IPPCRYPTOROOT='/opt/intel/oneapi/ippcp/2021.6.2'
ENV IPPROOT='/opt/intel/oneapi/ipp/2021.6.2'
ENV IPP_TARGET_ARCH='intel64'
ENV I_MPI_ROOT='/opt/intel/oneapi/mpi/2021.7.1'
ENV LD_LIBRARY_PATH='/opt/intel/oneapi/vpl/2022.2.5/lib:/opt/intel/oneapi/tbb/2021.7.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.7.1//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.1//lib/release:/opt/intel/oneapi/mpi/2021.7.1//lib:/opt/intel/oneapi/mkl/2022.2.1/lib/intel64:/opt/intel/oneapi/itac/2021.7.1/slib:/opt/intel/oneapi/ippcp/2021.6.2/lib/intel64:/opt/intel/oneapi/ipp/2021.6.2/lib/intel64:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/2021.7.1/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/dep/lib:/opt/intel/oneapi/dal/2021.7.1/lib/intel64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/x64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/2021.7.1/lib/cpu_gpu_dpcpp'
ENV LIBRARY_PATH='/opt/intel/oneapi/vpl/2022.2.5/lib:/opt/intel/oneapi/tbb/2021.7.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.7.1//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.1//lib/release:/opt/intel/oneapi/mpi/2021.7.1//lib:/opt/intel/oneapi/mkl/2022.2.1/lib/intel64:/opt/intel/oneapi/ippcp/2021.6.2/lib/intel64:/opt/intel/oneapi/ipp/2021.6.2/lib/intel64:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/dal/2021.7.1/lib/intel64:/opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/2022.2.1/linux/lib:/opt/intel/oneapi/clck/2021.7.1/lib/intel64:/opt/intel/oneapi/ccl/2021.7.1/lib/cpu_gpu_dpcpp'
ENV MANPATH='/opt/intel/oneapi/mpi/2021.7.1/man:/opt/intel/oneapi/itac/2021.7.1/man:/opt/intel/oneapi/debugger/2021.7.1/documentation/man:/opt/intel/oneapi/compiler/2022.2.1/documentation/en/man/common:/opt/intel/oneapi/clck/2021.7.1/man::'
ENV MKLROOT='/opt/intel/oneapi/mkl/2022.2.1'
ENV NLSPATH='/opt/intel/oneapi/mkl/2022.2.1/lib/intel64/locale/%l_%t/%N:/opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin/locale/%l_%t/%N'
ENV OCL_ICD_FILENAMES='libintelocl_emu.so:libalteracl.so:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/x64/libintelocl.so'
ENV ONEAPI_ROOT='/opt/intel/oneapi'
ENV PATH='/opt/intel/oneapi/vtune/2022.4.1/bin64:/opt/intel/oneapi/vpl/2022.2.5/bin:/opt/intel/oneapi/mpi/2021.7.1//libfabric/bin:/opt/intel/oneapi/mpi/2021.7.1//bin:/opt/intel/oneapi/mkl/2022.2.1/bin/intel64:/opt/intel/oneapi/itac/2021.7.1/bin:/opt/intel/oneapi/intelpython/latest/bin:/opt/intel/oneapi/intelpython/latest/condabin:/opt/intel/oneapi/inspector/2022.3.1/bin64:/opt/intel/oneapi/dev-utilities/2021.7.1/bin:/opt/intel/oneapi/debugger/2021.7.1/gdb/intel64/bin:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga/bin:/opt/intel/oneapi/compiler/2022.2.1/linux/bin/intel64:/opt/intel/oneapi/compiler/2022.2.1/linux/bin:/opt/intel/oneapi/clck/2021.7.1/bin/intel64:/opt/intel/oneapi/advisor/2022.3.1/bin64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
ENV PKG_CONFIG_PATH='/opt/intel/oneapi/vtune/2022.4.1/include/pkgconfig/lib64:/opt/intel/oneapi/vpl/2022.2.5/lib/pkgconfig:/opt/intel/oneapi/tbb/2021.7.1/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.7.1/lib/pkgconfig:/opt/intel/oneapi/mkl/2022.2.1/lib/pkgconfig:/opt/intel/oneapi/ippcp/2021.6.2/lib/pkgconfig:/opt/intel/oneapi/inspector/2022.3.1/include/pkgconfig/lib64:/opt/intel/oneapi/dpl/2021.7.2/lib/pkgconfig:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/../lib/pkgconfig:/opt/intel/oneapi/dal/2021.7.1/lib/pkgconfig:/opt/intel/oneapi/compiler/2022.2.1/lib/pkgconfig:/opt/intel/oneapi/ccl/2021.7.1/lib/pkgconfig:/opt/intel/oneapi/advisor/2022.3.1/include/pkgconfig/lib64:'
ENV PYTHONPATH='/opt/intel/oneapi/advisor/2022.3.1/pythonapi'
ENV SETVARS_COMPLETED='1'
ENV TBBROOT='/opt/intel/oneapi/tbb/2021.7.1/env/..'
ENV VTUNE_PROFILER_2022_DIR='/opt/intel/oneapi/vtune/2022.4.1'
ENV VTUNE_PROFILER_DIR='/opt/intel/oneapi/vtune/2022.4.1'
ENV VT_ADD_LIBS='-ldwarf -lelf -lvtunwind -lm -lpthread'
ENV VT_LIB_DIR='/opt/intel/oneapi/itac/2021.7.1/lib'
ENV VT_MPI='impi4'
ENV VT_ROOT='/opt/intel/oneapi/itac/2021.7.1'
ENV VT_SLIB_DIR='/opt/intel/oneapi/itac/2021.7.1/slib'
ENV _CE_CONDA=''
ENV _CE_M=''
