# Copyright (c) 2020-2021 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause

FROM ubuntu:20.04
COPY third-party-programs.txt /
RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
  rm -rf /var/lib/apt/lists/*
# repository to install Intel(R) oneAPI Libraries
RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | gpg --dearmor | tee /usr/share/keyrings/intel-oneapi-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get upgrade -y && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git cmake intel-basekit intel-hpckit  && \
  rm -rf /var/lib/apt/lists/*




ENV LANG=C.UTF-8
ENV ACL_BOARD_VENDOR_PATH='/opt/Intel/OpenCLFPGA/oneAPI/Boards'
ENV ADVISOR_2024_DIR='/opt/intel/oneapi/advisor/2024.1'
ENV APM='/opt/intel/oneapi/advisor/2024.1/perfmodels'
ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
ENV CCL_CONFIGURATION_PATH=''
ENV CCL_ROOT='/opt/intel/oneapi/ccl/2021.12'
ENV CLASSPATH='/opt/intel/oneapi/mpi/2021.12/share/java/mpi.jar'
ENV CMAKE_PREFIX_PATH='/opt/intel/oneapi/tbb/2021.12/env/..:/opt/intel/oneapi/mkl/2024.1/lib/cmake:/opt/intel/oneapi/ipp/2021.11/lib/cmake/ipp:/opt/intel/oneapi/dpl/2022.5/lib/cmake/oneDPL:/opt/intel/oneapi/dnnl/2024.1/lib/cmake:/opt/intel/oneapi/dal/2024.2:/opt/intel/oneapi/compiler/2024.1'
ENV CMPLR_ROOT='/opt/intel/oneapi/compiler/2024.1'
ENV CPATH='/opt/intel/oneapi/tbb/2021.12/env/../include:/opt/intel/oneapi/mpi/2021.12/include:/opt/intel/oneapi/mkl/2024.1/include:/opt/intel/oneapi/ippcp/2021.11/include:/opt/intel/oneapi/ipp/2021.11/include:/opt/intel/oneapi/dpl/2022.5/include:/opt/intel/oneapi/dpcpp-ct/2024.1/include:/opt/intel/oneapi/dnnl/2024.1/include:/opt/intel/oneapi/dev-utilities/2024.1/include:/opt/intel/oneapi/dal/2024.2/include/dal:/opt/intel/oneapi/compiler/2024.1/opt/oclfpga/include:/opt/intel/oneapi/ccl/2021.12/include'
ENV DALROOT='/opt/intel/oneapi/dal/2024.2'
ENV DAL_MAJOR_BINARY='2'
ENV DAL_MINOR_BINARY='0'
ENV DIAGUTIL_PATH='/opt/intel/oneapi/dpcpp-ct/2024.1/etc/dpct/sys_check/sys_check.sh:/opt/intel/oneapi/debugger/2024.1/etc/debugger/sys_check/sys_check.py:/opt/intel/oneapi/compiler/2024.1/etc/compiler/sys_check/sys_check.sh'
ENV DNNLROOT='/opt/intel/oneapi/dnnl/2024.1'
ENV DPL_ROOT='/opt/intel/oneapi/dpl/2022.5'
ENV FI_PROVIDER_PATH='/opt/intel/oneapi/mpi/2021.12/opt/mpi/libfabric/lib/prov:/usr/lib/x86_64-linux-gnu/libfabric'
ENV FPGA_VARS_ARGS=''
ENV FPGA_VARS_DIR='/opt/intel/oneapi/compiler/2024.1/opt/oclfpga'
ENV GDB_INFO='/opt/intel/oneapi/debugger/2024.1/share/info/'
ENV INFOPATH='/opt/intel/oneapi/debugger/2024.1/opt/debugger/lib'
ENV INTELFPGAOCLSDKROOT='/opt/intel/oneapi/compiler/2024.1/opt/oclfpga'
ENV INTEL_PYTHONHOME='/opt/intel/oneapi/debugger/2024.1/opt/debugger'
ENV IPPCP_TARGET_ARCH='intel64'
ENV IPPCRYPTOROOT='/opt/intel/oneapi/ippcp/2021.11'
ENV IPPROOT='/opt/intel/oneapi/ipp/2021.11'
ENV IPP_TARGET_ARCH='intel64'
ENV I_MPI_ROOT='/opt/intel/oneapi/mpi/2021.12'
ENV LD_LIBRARY_PATH='/opt/intel/oneapi/tbb/2021.12/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.12/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.12/lib:/opt/intel/oneapi/mkl/2024.1/lib:/opt/intel/oneapi/ippcp/2021.11/lib/:/opt/intel/oneapi/ipp/2021.11/lib:/opt/intel/oneapi/dpl/2022.5/lib:/opt/intel/oneapi/dnnl/2024.1/lib:/opt/intel/oneapi/debugger/2024.1/opt/debugger/lib:/opt/intel/oneapi/dal/2024.2/lib:/opt/intel/oneapi/compiler/2024.1/opt/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2024.1/opt/compiler/lib:/opt/intel/oneapi/compiler/2024.1/lib:/opt/intel/oneapi/ccl/2021.12/lib/'
ENV LIBRARY_PATH='/opt/intel/oneapi/tbb/2021.12/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.12/lib:/opt/intel/oneapi/mkl/2024.1/lib/:/opt/intel/oneapi/ippcp/2021.11/lib/:/opt/intel/oneapi/ipp/2021.11/lib:/opt/intel/oneapi/dpl/2022.5/lib:/opt/intel/oneapi/dnnl/2024.1/lib:/opt/intel/oneapi/dal/2024.2/lib:/opt/intel/oneapi/compiler/2024.1/lib:/opt/intel/oneapi/ccl/2021.12/lib/'
ENV MANPATH='/opt/intel/oneapi/mpi/2021.12/share/man:/opt/intel/oneapi/debugger/2024.1/share/man:/opt/intel/oneapi/compiler/2024.1/share/man:'
ENV MKLROOT='/opt/intel/oneapi/mkl/2024.1'
ENV NLSPATH='/opt/intel/oneapi/mkl/2024.1/share/locale/%l_%t/%N:/opt/intel/oneapi/compiler/2024.1/lib/compiler/locale/%l_%t/%N'
ENV OCL_ICD_FILENAMES='libintelocl_emu.so:libalteracl.so:/opt/intel/oneapi/compiler/2024.1/lib/libintelocl.so'
ENV ONEAPI_ROOT='/opt/intel/oneapi'
ENV PATH='/opt/intel/oneapi/vtune/2024.1/bin64:/opt/intel/oneapi/mpi/2021.12/bin:/opt/intel/oneapi/mkl/2024.1/bin/:/opt/intel/oneapi/dpcpp-ct/2024.1/bin:/opt/intel/oneapi/dev-utilities/2024.1/bin:/opt/intel/oneapi/debugger/2024.1/opt/debugger/bin:/opt/intel/oneapi/compiler/2024.1/opt/oclfpga/bin:/opt/intel/oneapi/compiler/2024.1/bin:/opt/intel/oneapi/advisor/2024.1/bin64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
ENV PKG_CONFIG_PATH='/opt/intel/oneapi/vtune/2024.1/include/pkgconfig/lib64:/opt/intel/oneapi/tbb/2021.12/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.12/lib/pkgconfig:/opt/intel/oneapi/mkl/2024.1/lib/pkgconfig:/opt/intel/oneapi/ippcp/2021.11/lib/pkgconfig:/opt/intel/oneapi/dpl/2022.5/lib/pkgconfig:/opt/intel/oneapi/dnnl/2024.1/lib/pkgconfig:/opt/intel/oneapi/dal/2024.2/lib/pkgconfig:/opt/intel/oneapi/compiler/2024.1/lib/pkgconfig:/opt/intel/oneapi/ccl/2021.12/lib/pkgconfig/:/opt/intel/oneapi/advisor/2024.1/include/pkgconfig/lib64:'
ENV PYTHONPATH='/opt/intel/oneapi/advisor/2024.1/pythonapi'
ENV SETVARS_COMPLETED='1'
ENV TBBROOT='/opt/intel/oneapi/tbb/2021.12/env/..'
ENV VTUNE_PROFILER_2024_DIR='/opt/intel/oneapi/vtune/2024.1'
ENV VTUNE_PROFILER_DIR='/opt/intel/oneapi/vtune/2024.1'
