# Copyright (c) 2020-2026 Intel Corporation.
# SPDX-License-Identifier: BSD-3-Clause

FROM ubuntu:24.04

ARG ONEAPI_VTUNE_VERSION="2025.10.1-14"

RUN apt-get update && apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl gpg-agent software-properties-common ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git file cmake && \
    rm -rf /var/lib/apt/lists/*

# repository to install Intel® oneAPI Libraries
RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/intel-oneapi-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list
# Repository to install Intel® Graphics Driver
ARG REPOSITORY="ppa:kobuk-team/intel-graphics"
RUN add-apt-repository -y ${REPOSITORY}

RUN apt-get update && apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        intel-oneapi-vtune=${ONEAPI_VTUNE_VERSION} intel-opencl-icd libze-intel-gpu1 libze1 libze-dev && \
    rm -rf /var/lib/apt/lists/*

ENV LANG="C.UTF-8"

ENV ONEAPI_ROOT='/opt/intel/oneapi'
ENV PATH='/opt/intel/oneapi/vtune/2025.10/bin64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
ENV PKG_CONFIG_PATH='/opt/intel/oneapi/vtune/2025.10/include/pkgconfig/lib64:'
ENV SETVARS_COMPLETED='1'
ENV VTUNE_PROFILER_2025_DIR='/opt/intel/oneapi/vtune/2025.10'
ENV VTUNE_PROFILER_DIR='/opt/intel/oneapi/vtune/2025.10'
